Neos:
  Neos:
    fusion:
      autoInclude:
        KaufmannDigital.EmailEditing: true
    userInterface:
      translation:
        autoInclude:
          KaufmannDigital.EmailEditing:
            - 'NodeTypes/*'
    nodeTypes:
      groups:
        emailEditing:
          label: 'Email-Editing'
          icon: 'envelope'
  Fusion:
    defaultContext:
      MJML: KaufmannDigital\EmailEditing\Fusion\Helper\MjmlHelper
