KaufmannDigital:
  EmailEditing:
    mjmlRendering:
      fusionPaths:
        'Neos.Fusion': 'resource://Neos.Fusion/Private/Fusion'
        'Neos.Neos': 'resource://Neos.Neos/Private/Fusion'
        'KaufmannDigital.EmailEditing': 'resource://KaufmannDigital.EmailEditing/Private/Fusion'