Neos:
  Neos:
    fusion:
      autoInclude:
        KaufmannDigital.EmailEditing: true
    userInterface:
      translation:
        autoInclude:
          KaufmannDigital.EmailEditing:
            - 'NodeTypes/*'
  Fusion:
    defaultContext:
      MJML: KaufmannDigital\EmailEditing\Fusion\Helper\MjmlHelper
